format = """\
$username\
$hostname\
$directory\
$kubernetes\
$git_branch\
$git_status\
$rust\
$character\
"""
add_newline = false
# right_prompt = true # TODO: requires fish/zsh

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
format = "[$symbol](bold) "
disabled = false

[username]
style_root = 'bold red'
style_user = 'yellow'
format = '[$user]($style)'

[hostname]
ssh_only = true
style = 'bold dimmed green'
format = "[ $hostname ]($style)"

[rust]
disabled = false
style = "202"
format = "[ $symbol($version)]($style)"
version_format = "${minor}"
detect_extensions = []

[directory]
truncation_length = 3
style = "white"
format = "[$path ]($style)"
truncate_to_repo = "false"
fish_style_pwd_dir_length = 5
# MISSING: cannot change the separator between dirs (looks cluttered)
# https://github.com/starship/starship/pull/1209 died
#separator = "î‚±"

[kubernetes]
symbol = "â˜¸ "
style = "27"
disabled = false
format = '[$symbol]($style)[$context( \($namespace\))](white)'

[git_branch]
style = "bold 38"
format = "[ $symbol]($style)[$branch](38)"
truncation_length = 24
truncation_symbol = "."

[git_status]
disabled = false
format = '[ $ahead_behind$modified$conflicted$stashed$deleted$renamed$staged$untracked]($style)'
style = "38"
conflicted = "ğŸ³ "
ahead = "â†‘$count "
behind = "â†“$count "
diverged = "â‡• "
untracked = "â€¦"
stashed = "âš‘ "
modified = '+$count '
staged = "â— "
renamed = "ğŸ‘… "
deleted = "ğŸ—‘ "
#up_to_date = "âœ” "

[line_break]
disabled = true
