[character]
symbol = "î‚°"
# PROBLEM: cannot get a consistent bg color across separators

[hostname]
ssh_only = true

[kubernetes]
symbol = "â˜¸ "
style = "bg:black bold blue"
disabled = false

[directory]
truncation_length = 3
style = "bg:black fg:bold white"
prefix = "î‚± "
truncate_to_repo = "false"

[git_branch]
symbol = "î‚  "
style = "bg:black bold purple"
truncation_length = 8
truncation_symbol = "."

[git_status]
conflicted = "ğŸ³"
ahead = "â†‘"
behind = "â†“"
diverged = "â‡•"
untracked = "â€¦"
stashed = "âš‘"
modified = "+"
# DIDNT FULLY TWEAK THIS
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[line_break]
disabled = true
